# 📘 Тема 1: Четене и обработка на данни

---

## 1. Въвеждане на данни ръчно с NumPy
В началото зареждаме библиотеката **NumPy** с краткото име `np`. 


In [2]:
import numpy as np

u = [0, 1.2, 2.4, 3.2, 4, 5, 6, 7, 8, 9]
v = [1.5, 2.8, 2, 5, 7, 8, 8.5, 9.2, 10.4, 12.5]

# Отпечатване на стойностите
print(u, v)

# Отпечатване на стойностите с цикъл
for i in range(0, 10):
    print(u[i], ' ', v[i])

[0, 1.2, 2.4, 3.2, 4, 5, 6, 7, 8, 9] [1.5, 2.8, 2, 5, 7, 8, 8.5, 9.2, 10.4, 12.5]
0   1.5
1.2   2.8
2.4   2
3.2   5
4   7
5   8
6   8.5
7   9.2
8   10.4
9   12.5


- `range(0, 10)` – създава диапазон от стойности от 0 до 9.
- `print(u[i], ' ', v[i])` – отпечатва стойностите на `u` и `v` по индекси.
---

## 2. Използване на `np.array()`
Методът `np.array()` преобразува обект в `numpy array`.


In [ ]:
x = np.array([0, 1.2, 2.4, 3.2, 4, 5, 6, 7, 8, 9])
y = np.array([1.5, 2.8, 2, 5, 7, 8, 8.5, 9.2, 10.4, 12.5])

print(x)
print(y)

- `np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)`
    - `object` – списък или друга структура от данни.
    - `dtype` – тип на елементите (`int`, `float`, `bool` и т.н.).
    - `copy` – ако е `True`, се копират данните, ако е `False`, се използват оригиналните данни.
---

## 3. Четене на CSV файл с `pandas.read_csv()`


In [4]:
import pandas as pd

dataset = pd.read_csv("lab/insurance.csv")
data = dataset.values
x = data[:, 0]
y = data[:, 1]

print(x[:10])
print(y[:10])

[108.  19.  13. 124.  40.  57.  23.  14.  45.  10.]
[392.5  46.2  15.7 422.2 119.4 170.9  56.9  77.5 214.   65.3]


- `pd.read_csv(filepath, delimiter=',', header='infer')`
    - `filepath` – пътят до файла.
    - `delimiter` – разделител между колоните.
---

## 4. Четене на текстови файлове с `numpy.loadtxt()`


In [5]:
data = np.loadtxt('lab/ex2data1.txt', delimiter=',')
x = data[:, 0:2]
y = data[:, 2]

print(x[:5])
print(y[:5])

[[34.62365962 78.02469282]
 [30.28671077 43.89499752]
 [35.84740877 72.90219803]
 [60.18259939 86.3085521 ]
 [79.03273605 75.34437644]]
[0. 0. 0. 1. 1.]


### Обяснение:
- `np.loadtxt(fname, delimiter=None, skiprows=0, usecols=None, dtype=float)`
---